import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from "@/features/navigation/components/theme-provider";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

const walone_bold = localFont({
  src: "../../public/fonts/Z06-Walone-Bold.ttf",
  display: "swap",
  variable: "--font-z06-walone-bold",
});

export const metadata: Metadata = {
  title: "Job Portal",
  description: "Generated by Kaung Satt Hein",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased 
    ${openSans.className} 
  `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
