import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from "@/features/navigation/components/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "@/lib";
import { ToastWrapper } from "@/components/common";
import NavBar from "@/features/navigation/NavBar";
import Footer from "@/features/Footer";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

const walone_bold = localFont({
  src: "../../../public/fonts/Z06-Walone-Bold.ttf",
  display: "swap",
  variable: "--font-z06-walone-bold",
});

export const metadata: Metadata = {
  title: "Job Portal",
  description: "Generated by Kaung Satt Hein",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = await params;
  const messages = getMessages(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`antialiased ${openSans.variable} ${walone_bold.variable}`}
        style={{
          fontFamily:
            locale === "en"
              ? "var(--font-dm-sans)"
              : "var(--font-z06-walone-bold)",
        }}
      >
        <ToastWrapper />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            {children}
            {/* <Footer /> */}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
